# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines

pool:
  vmImage: 'ubuntu-latest'

parameters:
  python_versions: [ 'py2' ]


steps:
  - ${{ each version in parameters.versions }}:
    # Checkout Git Repo
    - checkout: self
      clean: true

    - script: python -m pip install --user pyyaml
      displayName: 'Install PyYaml'

    - script: python config/generate_addon.py ${{ version }}
      displayName: 'Create addon.xml'

    - script: ls .
      displayName: 'List project dir'
