# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
# Checkout Git Repo
- checkout: self
  clean: true

# Modify
- task: FileTransform@1
  inputs:
    folderPath: $(System.DefaultWorkingDirectory)
    xmlTransformationRules: '-transform ../.config/addon.xml.py2 -xml ../.config/addon.xml.template -result ../addon.xml'
    fileType: 'xml'

- script: ls .
  displayName: 'list repo files'

- script: ls .config
  displayName: 'list config files'

#- script: cat addon.xml
#  displayName: 'Cat addon file'

#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'
