parameters:
  python_versions : []

steps:
  - ${{ each version in parameters.py_versions }}:
    - task: usePythonVersion@0
      inputs:
        versionSpec: '3.6'

    # Checkout Git Repo
    - checkout: self
      clean: true

    - script: pwd
      displayName: 'dir'

    - script: python3 -m pip install --user pyyaml
      displayName: 'Install PyYaml'

    - script: ls -la
      displayName: 'looky'

    - script: python3 jellyfin-kodi/.config/generate_xml.py ${{ version }}
      displayName: 'Create ${{ version }} addon.xml'

    - script: cat jellyfin-kodi/addon.xml
      displayName: 'display ${{ version }} addon.xml'

    - script: ls -la
      displayName: 'looky2'

    - script: ls -la jellyfin-kodi
      displayName: 'looky3'

