parameters:
  python_versions : []

steps:
  - ${{ each version in parameters.py_versions }}:
    # Checkout Git Repo
    - checkout: self
      clean: true

    - script: python -m pip install --user pyyaml
      displayName: 'Install PyYaml'

    - script: python .config/generate_addon.py ${{ version }}
      displayName: 'Create addon.xml'

    - script: ls .
      displayName: 'List project dir'

