parameters:
  python_versions : []

steps:
  - ${{ each version in parameters.py_versions }}:
    - task: usePythonVersion@0
      inputs:
        versionSpec: '3.6'

    # Checkout Git Repo
    - checkout: self
      clean: true

    - script: python3 -m pip install --user pyyaml
      displayName: 'Install PyYaml'

    - script: python3 .config/generate_addon.py ${{ version }}
      displayName: 'Create addon.xml'

    - script: ls .
      displayName: 'List project dir'

